### ISSUE TITLE
BAD CODE

### ISSUE THREAD

**Issue by ombhatt2** [RidwanA123/MEMEZ#1]
I think improvments can be made and is this yours?

**Comment by RidwanA123** [comment]
> COPIED CODE COPIED CODE !

First of all, this is forked because it's not available on the internet anymore and I put it in the GitHub so that my friends can download it and test it on their virtual machines. I never said this was my code.

Secondly, you do not know dog fucking shit about what this is and what it does. If you are stupid enough, go ahead and download it and run it.

Finally, all your repositories are copied from other sources and you come here you run your shitty mouth in my GitHub without reason. You are an inbred child and you need some friends. 

Get off your fucking computer/Discord and see some sunlight for once

- Ridwan

**Comment by JanikThePanic** [comment]
Om, as Ridwan said,
"First of all, this is forked because it's not available on the internet anymore and I put it in the GitHub so that my friends can download it and test it on their virtual machines. I never said this was my code.

Secondly, you do not know dog fucking shit about what this is and what it does. If you are stupid enough, go ahead and download it and run it.

Finally, all your repositories are copied from other sources and you come here you run your shitty mouth in my GitHub without reason. You are an inbred child and you need some friends.

Get off your fucking computer/Discord and see some sunlight for once"

**Comment by pranjaln16** [comment]
> COPIED CODE COPIED CODE !

You're the epitome of a clown. Stop yourself.

**Comment by Luke-zhang-04** [comment]
> COPIED CODE COPIED CODE !

He never said it was his?
From the README:
> made by the viewer of Danooct1
he never takes credit. Like come on dude.

**Comment by ombhatt2** [comment]
> > COPIED CODE COPIED CODE !
> 
> First of all, this is forked because it's not available on the internet anymore and I put it in the GitHub so that my friends can download it and test it on their virtual machines. I never said this was my code.
> 
> Secondly, you do not know dog fucking shit about what this is and what it does. If you are stupid enough, go ahead and download it and run it.
> 
> Finally, all your repositories are copied from other sources and you come here you run your shitty mouth in my GitHub without reason. You are an inbred child and you need some friends.
> 
> Get off your fucking computer/Discord and see some sunlight for once
> 
> * Ridwan

Excuse me?

**Comment by ombhatt2** [comment]
Guys, I did not mean to be rough on you I am just asking if this is yours and improvements can be made. Do not take it the other way around
please
OM

**Comment by JanikThePanic** [comment]
Your original words (Before you edited the issue); _"COPIED CODE COPIED CODE !"_
In no way are you kindly saying "_if this is yours and improvements"_.
Like dude, OM my God, go outside, buddy. Uninstall Discord and get some friends.

**Comment by Luke-zhang-04** [comment]
![image](https://user-images.githubusercontent.com/55749227/109079653-3e44c680-76cd-11eb-91a0-d9ef7d2d5eb6.png)
There's edit history btw

**Comment by RidwanA123** [comment]
> Guys, I did not mean to be rough on you I am just asking if this is yours and improvements can be made. Do not take it the other way around
> please
> OM

Stop trying to act smart and just never come on here again. How the fuck did you even find my GitHub?

**Comment by ombhatt2** [comment]
Please stop and this code you have is illegal its hacking please don't do that!

**Comment by RidwanA123** [comment]
> Please stop and this code you have is illegal its hacking please don't do that!

Again, why are you still here?

**Comment by RidwanA123** [comment]
> Please stop and this code you have is illegal its hacking please don't do that!

Why do you have a GitHub then if you don't know what my code does.

**Comment by ombhatt2** [comment]
> > Please stop and this code you have is illegal its hacking please don't do that!
> 
> Again, why are you still here?

Because I can be here

**Comment by ombhatt2** [comment]
> > Please stop and this code you have is illegal its hacking please don't do that!
> 
> Why do you have a GitHub then if you don't know what my code does.

it literally says on your description hacking"

**Comment by RidwanA123** [comment]
> > > Please stop and this code you have is illegal its hacking please don't do that!
> > 
> > 
> > Why do you have a GitHub then if you don't know what my code does.
> 
> it literally says on your description hacking"

Get your eyes checked...

**Comment by Luke-zhang-04** [comment]
> > > Please stop and this code you have is illegal its hacking please don't do that!
> > 
> > 
> > Again, why are you still here?
> 
> Because I can be here

why can't you leave him alone. This is so dumb. It's a bunch of high schoolers arguing like children over something that barely even matters. @RidwanA123 just close the issue.

**Comment by Luke-zhang-04** [comment]
Last question, if this is "illegal hacking", why does Om have a fork of it? 
![image](https://user-images.githubusercontent.com/55749227/109224217-a78a0f80-7789-11eb-90ef-c59e3b9888ef.png)
https://github.com/Omcodez1503/MEMEZ
